import type { AuthLabels } from './labels'

/**
 * 인증 화면의 한국어 문구(선택 — 쓰지 않으면 번들에 들어가지 않는다). `AuthLabels` 타입이 모든 키를 요구하므로 빠지면 컴파일이 실패한다.
 * 영어는 `defaultAuthLabels`. 해요체 — 앱 문체가 다르면 `{ ...koAuthLabels, signInTitle: '…' }` 로 덮는다.
 */
export const koAuthLabels: AuthLabels = {
  email: '이메일',
  password: '비밀번호',
  newPassword: '새 비밀번호',
  currentPassword: '현재 비밀번호',
  displayName: '표시 이름',
  or: '또는',
  back: '뒤로',
  continue: '계속',
  submitting: '처리 중',
  save: '저장',
  saved: '저장했어요',
  cancel: '취소',
  copyHint: '복사',
  errorInvalidCredentials: '이메일 또는 비밀번호가 맞지 않아요.',
  errorEmailNotVerified: '먼저 이메일 주소를 인증해 주세요. 링크를 다시 보내 드릴 수 있어요.',
  errorSuspended: '정지된 계정이에요.',
  errorBlocked: '이 계정은 쓸 수 없어요.',
  errorTooManyAttempts: '시도가 너무 많아요. 잠시 뒤에 다시 해 주세요.',
  errorRateLimited: '요청이 너무 많아요. 잠시 뒤에 다시 해 주세요.',
  errorRetryIn: (seconds) => `${seconds}초 뒤에 다시 시도할 수 있어요.`,
  errorTokenInvalid: '링크가 올바르지 않거나 만료됐거나 이미 썼어요.',
  errorEmailTaken: '이미 가입된 이메일이에요.',
  errorSignUpClosed: '지금은 가입을 받지 않아요.',
  errorCaptcha: '확인을 통과하지 못했어요. 다시 해 주세요.',
  errorCurrentPassword: '현재 비밀번호가 맞지 않아요.',
  errorReauth: '비밀번호 또는 확인 코드가 맞지 않아요.',
  errorReauthRequired: '먼저 본인 확인이 필요해요. 메일로 링크를 보내 드려요.',
  errorLastMethod: '마지막 로그인 수단이에요. 다른 수단을 먼저 추가해 주세요.',
  errorLastAdmin: '관리자는 최소 한 명이 있어야 해요.',
  errorSelfAction: '내 계정에는 할 수 없는 동작이에요.',
  errorIdentityTaken: '그 계정은 이미 다른 사람과 연결돼 있어요.',
  errorIdentityExists: '이미 연결된 로그인 수단이에요.',
  errorSocialConflict:
    '같은 이메일의 계정이 이미 있어요. 그 계정으로 로그인한 뒤 설정에서 이 서비스를 연결해 주세요.',
  errorValidation: '표시된 칸을 확인해 주세요.',
  errorNetwork: '연결할 수 없어요. 다시 시도해 주세요.',
  errorGeneric: '문제가 생겼어요. 다시 시도해 주세요.',
  errorReference: (traceId) => `참조 번호: ${traceId}`,
  sessionEnded: {
    expired: '로그인이 만료됐어요. 다시 로그인해 주세요.',
    'reuse-detected': '다른 곳에서 세션이 쓰여 로그아웃됐어요. 다시 로그인해 주세요.',
    suspended: '정지된 계정이에요.',
    unauthenticated: '계속하려면 로그인해 주세요.',
  },
  passwordRequirementsTitle: '비밀번호는 이래야 해요',
  passwordStrengthLabel: '강도',
  passwordStrength: ['비어 있음', '약함', '보통', '좋음', '강함'],
  passwordRule: {
    TOO_SHORT: '글자 수가 충분해요',
    TOO_LONG: '너무 길지 않아요',
    NEEDS_LETTER: '문자 포함',
    NEEDS_DIGIT: '숫자 포함',
    NEEDS_SYMBOL: '기호 포함',
    CONTAINS_EMAIL: '이메일 일부가 들어 있지 않아요',
    TOO_COMMON: '흔한 비밀번호가 아니에요',
    BREACHED: '유출된 적 없는 비밀번호예요',
  },
  requirementMet: '충족',
  requirementUnmet: '아직 아님',
  show: '보기',
  hide: '숨기기',
  signInTitle: '로그인',
  signInSubtitle: '노트와 첨부 파일을 한곳에서 정리하세요.',
  signInSubmit: '로그인',
  signInForgot: '비밀번호를 잊으셨나요?',
  signInNoAccount: '계정이 없나요?',
  signInCreateAccount: '가입하기',
  signInWithProvider: (provider) => `${provider}로 계속하기`,
  signInMagicLink: '이메일로 로그인 링크 받기',
  signInMagicLinkHelp: '메일로 링크를 보내 드려요. 비밀번호는 필요 없어요.',
  signInMagicLinkSubmit: '링크 보내기',
  signInUsePassword: '비밀번호로 로그인',
  signInResendVerification: '인증 메일 다시 받기',
  signInVerificationResent: '인증이 필요한 주소라면 새 메일이 가고 있어요.',
  providerNames: { google: '구글', kakao: '카카오', naver: '네이버' },
  signUpTitle: '계정 만들기',
  signUpSubtitle: '1분이면 끝나요.',
  signUpSubmit: '가입하기',
  signUpHaveAccount: '이미 계정이 있나요?',
  signUpSignIn: '로그인',
  signUpClosedTitle: '지금은 가입을 받지 않아요',
  signUpConsentRequired: '필수',
  signUpCaptcha: '보안 확인',
  checkEmailTitle: '메일함을 확인해 주세요',
  checkEmailBody: (email) => `${email} 로 링크를 보냈어요. 열어서 계속해 주세요.`,
  checkEmailSpam: '아직 안 왔나요? 스팸함도 살펴보세요.',
  checkEmailResend: '다시 보내기',
  checkEmailResent: '다시 보냈어요.',
  checkEmailResendIn: (seconds) => `${seconds}초 뒤에 다시 보낼 수 있어요`,
  checkEmailWrongAddress: '주소를 잘못 썼나요? 처음부터',
  verifyEmailTitle: '이메일 인증',
  verifyEmailChecking: '링크를 확인하는 중',
  verifyEmailDone: '이메일을 인증했어요. 이제 로그인할 수 있어요.',
  verifyEmailDoneAction: '로그인하러 가기',
  verifyEmailInvalidTitle: '쓸 수 없는 링크예요',
  verifyEmailInvalidBody:
    '만료됐거나 이미 쓴 링크일 수 있어요. 이메일을 적으면 새 링크를 보내 드려요.',
  verifyEmailResendSubmit: '새 링크 보내기',
  magicLinkTitle: '로그인하는 중',
  magicLinkChecking: '링크를 확인하는 중',
  magicLinkInvalidTitle: '쓸 수 없는 로그인 링크예요',
  magicLinkInvalidBody: '만료됐거나 이미 쓴 링크일 수 있어요. 새 링크를 요청해 주세요.',
  magicLinkRequestNew: '새 링크 요청',
  magicLinkSentTitle: '메일함을 확인해 주세요',
  confirmEmailChangeTitle: '새 이메일 확인',
  confirmEmailChangeChecking: '변경을 확인하는 중',
  confirmEmailChangeDone:
    '이메일 주소를 바꿨어요. 모든 기기에서 로그아웃됐으니 새 주소로 다시 로그인해 주세요.',
  confirmEmailChangeInvalidBody: '링크가 올바르지 않거나 만료됐거나 이미 썼어요.',
  confirmReauthTitle: '본인 확인',
  confirmReauthChecking: '본인 확인을 마치는 중',
  confirmReauthEmailChanged:
    '확인했어요. 새 주소로 링크를 보냈어요 — 그 링크를 열면 이메일이 바뀌어요.',
  confirmReauthStashed:
    '확인했어요. 이 브라우저에서 시작한 작업이 아니에요. 여기서 계정 설정을 열어 한 번 더 제출하거나, 작업을 시작한 탭으로 돌아가세요.',
  confirmReauthStashedPassword:
    '확인했어요. 계정 설정으로 가서 새 비밀번호를 한 번 더 입력하면 끝나요.',
  confirmReauthStashedSocial: '확인했어요. 계정 설정으로 가서 연결 버튼을 한 번 더 누르면 끝나요.',
  confirmReauthSettings: '계정 설정 열기',
  confirmReauthHandedOff:
    '확인했어요. 작업을 시작한 탭에서 알아서 이어 가요 — 이 탭은 닫아도 돼요.',
  methodsLoading: '로그인 방법을 확인하는 중',
  methodsFailed:
    '쓸 수 있는 로그인 방법을 확인하지 못했어요. 기본 방법을 보여 드려요 — 빠진 게 있으면 다시 시도하세요.',
  methodsRetry: '다시 시도',
  linkPasswordHint: (provider) => `${provider} 를 계정에 연결하려면 현재 비밀번호를 입력하세요.`,
  reauthHint: '비밀번호 없이 로그인하는 계정이에요. 저장하기 전에 확인 링크를 메일로 보내 드려요.',
  reauthSentTitle: '메일을 확인해 주세요',
  reauthSentBody: (email) => `${email} 로 확인 링크를 보냈어요. 링크를 열면 이 작업이 이어져요.`,
  reauthResend: '링크 다시 보내기',
  reauthReadyTitle: '본인 확인을 마쳤어요',
  reauthReadyBody: '한 번 더 제출하면 끝나요 — 확인은 잠시 동안만 유효해요.',
  confirmReauthInvalidTitle: '이 링크는 쓸 수 없어요',
  confirmReauthInvalidBody:
    '올바르지 않거나 만료됐거나 이미 쓴 링크예요. 계정 설정에서 작업을 다시 시작하면 새 링크를 보내 드려요.',
  forgotTitle: '비밀번호 재설정',
  forgotSubtitle: '이메일을 적으면 재설정 링크를 보내 드려요.',
  forgotSubmit: '링크 보내기',
  forgotSentTitle: '메일함을 확인해 주세요',
  forgotSentBody: (email) => `${email} 에 계정이 있다면 재설정 링크가 가고 있어요.`,
  resetTitle: '새 비밀번호 정하기',
  resetSubtitle: '모든 기기에서 로그아웃돼요.',
  resetSubmit: '비밀번호 정하기',
  resetDoneTitle: '비밀번호를 바꿨어요',
  resetDoneBody: '새 비밀번호로 로그인해 주세요.',
  resetInvalidTitle: '쓸 수 없는 링크예요',
  resetInvalidBody: '만료됐거나 이미 쓴 링크일 수 있어요. 새 링크를 요청해 주세요.',
  resetRequestNew: '새 링크 요청',
  backToSignIn: '로그인으로 돌아가기',
  callbackChecking: '로그인을 마무리하는 중',
  callbackFailedTitle: '로그인을 마치지 못했어요',
  callbackFailedBody: '제공자가 로그인을 확인해 주지 않았어요. 다시 시도해 주세요.',
  callbackConflictTitle: '이미 계정이 있어요',
  callbackConflictBody:
    '그 이메일은 다른 로그인 수단으로 이미 가입돼 있어요. 그 수단으로 로그인한 뒤 계정 설정에서 이 서비스를 연결해 주세요.',
  suspendedTitle: '정지된 계정이에요',
  suspendedBody: '이 계정은 정지됐어요. 잘못이라고 생각하면 문의해 주세요.',
  blockedTitle: '접근할 수 없어요',
  blockedBody: '이 페이지를 쓸 권한이 없어요.',
  contactSupport: '문의하기',
  settingsTitle: '계정',
  settingsIndexLabel: '계정 항목',
  sectionProfile: '프로필',
  sectionPassword: '비밀번호',
  sectionEmail: '이메일 주소',
  sectionMethods: '로그인 수단',
  sectionSessions: '로그인한 기기',
  sectionDelete: '계정 삭제',
  profileLocale: '언어',
  profileTimeZone: '시간대',
  profileLocaleDefault: '정하지 않음',
  profileSaved: '프로필을 저장했어요.',
  passwordChangeSubmit: '비밀번호 바꾸기',
  passwordSetTitle: '비밀번호 정하기',
  passwordSetHint: '지금은 비밀번호 없이 로그인하고 있어요. 비밀번호를 더할 수 있어요.',
  passwordChanged: '비밀번호를 바꿨어요. 다른 기기는 로그아웃됐어요.',
  passwordOtherSessionsNote: '바꾸면 다른 기기는 로그아웃돼요.',
  emailCurrent: '현재 주소',
  emailVerified: '인증됨',
  emailUnverified: '인증 안 됨',
  emailNew: '새 이메일',
  emailChangeSubmit: '이메일 바꾸기',
  emailPendingTitle: '변경을 확인해 주세요',
  emailPendingBody: (email, until) =>
    `${email} 로 링크를 보냈어요. 링크를 열면 주소가 바뀌어요${until ? ` (링크는 ${until} 까지 유효해요)` : ''}. 메일이 안 오면 아래에서 다시 요청하세요.`,
  emailRequested: '그 주소를 쓸 수 있다면 확인 링크가 가고 있어요.',
  methodsDescription: '이 계정에 로그인할 수 있는 방법이에요.',
  methodsLastProtected: '로그인 수단은 하나 이상 있어야 해서 이 수단은 뗄 수 없어요.',
  methodNames: { password: '비밀번호', magic_link: '이메일 링크' },
  methodLastUsed: (when) => `마지막 사용 ${when}`,
  methodNeverUsed: '아직 쓰지 않았어요',
  methodUnlink: '해제',
  methodLink: (provider) => `${provider} 연결`,
  methodUnlinkTitle: (method) => `${method} 수단을 해제할까요?`,
  methodUnlinkBody: '해제하면 이 수단으로는 로그인할 수 없어요.',
  methodUnlinked: '해제했어요.',
  methodLinked: '연결했어요.',
  sessionsDescription: '이 계정에 로그인한 기기예요.',
  sessionsCurrent: '이 기기',
  sessionsRevoke: '로그아웃',
  sessionsRevokeOthers: '다른 모든 기기 로그아웃',
  sessionsRevoked: '로그아웃했어요.',
  sessionsUnknownDevice: '알 수 없는 기기',
  sessionsLastUsed: (when) => `마지막 사용 ${when}`,
  sessionsEmpty: '다른 세션이 없어요.',
  deleteTitle: '계정 삭제',
  deleteGraceNotice: (days) =>
    `계정은 바로 삭제 처리되고 데이터는 ${days}일 뒤에 지워져요. 그 안에는 관리자가 되살릴 수 있어요.`,
  deletePasswordHint: '본인 확인을 위해 비밀번호를 입력해 주세요.',
  deleteMailHint: '비밀번호 없이 로그인하는 계정이라 확인 링크를 메일로 보내 드려요.',
  deleteMailSend: '링크 메일 받기',
  deleteMailSent: '링크를 보냈어요. 링크를 열거나 아래에 확인 코드를 붙여 넣어 주세요.',
  deleteTokenLabel: '확인 코드',
  deleteButton: '내 계정 삭제',
  deleteDialogTitle: '계정을 삭제할까요?',
  deleteDialogBody: '모든 기기에서 로그아웃돼요. 직접 되돌릴 수 없어요.',
  deleteTypedPhrase: '삭제',
  deleteTypedLabel: '확인하려면 「삭제」를 입력하세요',
  deleteConfirm: '계정 삭제',
  deleteScheduled: (date) => `${date} 에 계정 데이터가 지워질 예정이에요.`,
  adminTitle: '계정 관리',
  adminSearch: '이메일로 찾기',
  adminStatusFilter: '상태',
  adminStatusAll: '전체',
  adminColumns: {
    email: '이메일',
    name: '이름',
    status: '상태',
    roles: '역할',
    created: '가입일',
    lastLogin: '마지막 로그인',
    actions: '동작',
  },
  adminStatus: { ACTIVE: '정상', SUSPENDED: '정지', DELETED: '삭제됨' },
  adminSuspend: '정지',
  adminUnsuspend: '정지 해제',
  adminRestore: '복구',
  adminGrantRole: (role) => `${role} 역할 주기`,
  adminRevokeRole: (role) => `${role} 역할 빼기`,
  adminSuspendTitle: (email) => `${email} 을(를) 정지할까요?`,
  adminSuspendReason: '사유(기록용, 본인에게는 보이지 않아요)',
  adminEmpty: '맞는 계정이 없어요.',
  adminCaption: '계정 목록',
  adminPage: (page, pages) => `${page} / ${pages} 쪽`,
  adminPrevious: '이전',
  adminNext: '다음',
  adminPurgeAfter: (date) => `${date} 에 지워짐`,
}
