import type { AuthLabels } from './labels'

/**
 * 인증 화면의 한국어 문구(선택 — 쓰지 않으면 번들에 들어가지 않는다). `AuthLabels` 타입이 모든 키를 요구하므로 빠지면 컴파일이 실패한다.
 * 영어는 `defaultAuthLabels`. 해요체 — 앱 문체가 다르면 `{ ...koAuthLabels, signInTitle: '…' }` 로 덮는다.
 */
export const koAuthLabels: AuthLabels = {
  email: '이메일',
  password: '비밀번호',
  newPassword: '새 비밀번호',
  currentPassword: '현재 비밀번호',
  displayName: '표시 이름',
  or: '또는',
  back: '뒤로',
  continue: '계속',
  submitting: '처리 중',
  save: '저장',
  saved: '저장했어요',
  cancel: '취소',
  copyHint: '복사',
  errorInvalidCredentials: '이메일 또는 비밀번호가 맞지 않아요.',
  errorEmailNotVerified:
    '이메일 인증이 끝나지 않은 계정이에요. 다시 가입하고 메일로 받은 인증번호를 입력해 주세요.',
  errorSuspended: '정지된 계정이에요.',
  errorBlocked: '이 계정은 쓸 수 없어요.',
  errorTooManyAttempts: '시도가 너무 많아요. 잠시 뒤에 다시 해 주세요.',
  errorRateLimited: '요청이 너무 많아요. 잠시 뒤에 다시 해 주세요.',
  errorRetryIn: (seconds) => `${seconds}초 뒤에 다시 시도할 수 있어요.`,
  errorTokenInvalid: '링크가 올바르지 않거나 만료됐거나 이미 썼어요.',
  errorEmailTaken: '이미 가입된 이메일이에요.',
  errorSignUpClosed: '지금은 가입을 받지 않아요.',
  errorCaptcha: '확인을 통과하지 못했어요. 다시 해 주세요.',
  errorCurrentPassword: '현재 비밀번호가 맞지 않아요.',
  errorReauth: '본인 확인이 통과되지 않았어요. 다시 시도해 주세요.',
  errorReauthRequired: '먼저 본인 확인이 필요해요.',
  errorLastMethod: '마지막 로그인 수단이에요. 다른 수단을 먼저 추가해 주세요.',
  errorLastAdmin: '관리자는 최소 한 명이 있어야 해요.',
  errorSelfAction: '내 계정에는 할 수 없는 동작이에요.',
  errorIdentityTaken: '그 계정은 이미 다른 사람과 연결돼 있어요.',
  errorIdentityExists: '이미 연결된 로그인 수단이에요.',
  errorConsentRequired: '가입하는 사이 약관이 바뀌었어요. 바뀐 내용을 읽고 다시 동의해 주세요.',
  errorSocialRequest:
    '로그인을 안전하게 시작하지 못했어요. 페이지를 새로 고치고 다시 시도해 주세요.',
  errorSocialCode: '이 로그인은 만료됐거나 이미 쓰였어요. 처음부터 다시 시작해 주세요.',
  errorSocialGateway: '제공자가 지금 응답하지 않아요. 잠시 뒤에 다시 시도해 주세요.',
  errorPkceUnavailable:
    '이 브라우저에서는 이 제공자로 안전한 로그인을 시작할 수 없어요. 최신 브라우저에서 https(또는 localhost) 주소로 열어 주세요.',
  errorSocialConflict:
    '같은 이메일의 계정이 이미 있어요. 그 계정으로 로그인한 뒤 설정에서 이 서비스를 연결해 주세요.',
  errorValidation: '표시된 칸을 확인해 주세요.',
  errorNetwork: '연결할 수 없어요. 다시 시도해 주세요.',
  errorGeneric: '문제가 생겼어요. 다시 시도해 주세요.',
  errorReference: (traceId) => `참조 번호: ${traceId}`,
  sessionEnded: {
    expired: '로그인이 만료됐어요. 다시 로그인해 주세요.',
    'reuse-detected': '다른 곳에서 세션이 쓰여 로그아웃됐어요. 다시 로그인해 주세요.',
    suspended: '정지된 계정이에요.',
    unauthenticated: '계속하려면 로그인해 주세요.',
  },
  passwordRequirementsTitle: '비밀번호는 이래야 해요',
  passwordStrengthLabel: '강도',
  passwordStrength: ['비어 있음', '약함', '보통', '좋음', '강함'],
  passwordRule: {
    TOO_SHORT: '글자 수가 충분해요',
    TOO_LONG: '너무 길지 않아요',
    NEEDS_LETTER: '문자 포함',
    NEEDS_DIGIT: '숫자 포함',
    NEEDS_SYMBOL: '기호 포함',
    CONTAINS_EMAIL: '이메일 일부가 들어 있지 않아요',
    TOO_COMMON: '흔한 비밀번호가 아니에요',
    BREACHED: '유출된 적 없는 비밀번호예요',
  },
  requirementMet: '충족',
  requirementUnmet: '아직 아님',
  show: '보기',
  hide: '숨기기',
  signInTitle: '로그인',
  signInSubtitle: '노트와 첨부 파일을 한곳에서 정리하세요.',
  signInSubmit: '로그인',
  signInForgot: '비밀번호를 잊으셨나요?',
  signInNoAccount: '계정이 없나요?',
  signInCreateAccount: '가입하기',
  signInWithProvider: (provider) => `${provider}로 계속하기`,
  signInMagicLink: '이메일로 로그인 링크 받기',
  signInMagicLinkHelp: '메일로 링크를 보내 드려요. 비밀번호는 필요 없어요.',
  signInMagicLinkSubmit: '링크 보내기',
  signInUsePassword: '비밀번호로 로그인',
  providerNames: { google: 'Google', line: 'LINE', x: 'X', kakao: '카카오', naver: '네이버' },
  // 조사는 이름의 받침에 달려 있다 — 알려진 제공자는 문장째 적는다(LINE 은 「라인」이라 읽혀 `으로`)
  providerSignInText: {
    google: 'Google로 계속하기',
    line: 'LINE으로 계속하기',
    x: 'X로 계속하기',
    kakao: '카카오로 계속하기',
    naver: '네이버로 계속하기',
  },
  signUpTitle: '계정 만들기',
  signUpSubtitle: '1분이면 끝나요.',
  signUpSubmit: '가입하기',
  signUpHaveAccount: '이미 계정이 있나요?',
  signUpSignIn: '로그인',
  signUpClosedTitle: '지금은 가입을 받지 않아요',
  signUpConsentRequired: '필수',
  signUpCaptcha: '보안 확인',
  codeTitle: '인증번호 6자리를 입력해 주세요',
  codeBody: (email) =>
    `${email} 로 인증번호를 보냈어요. 10분 안에 입력해 주세요 — 다른 사람에게 알려 주지 마세요.`,
  codeGroupLabel: '인증번호',
  codeDigit: (position, total) => `${total}자리 중 ${position}번째`,
  codeInvalid: (left) =>
    left === undefined
      ? '인증번호가 맞지 않아요.'
      : `인증번호가 맞지 않아요. ${left}번 더 시도할 수 있어요.`,
  codeExpired: '인증번호가 만료됐거나 다 썼어요. 처음부터 다시 받아 주세요.',
  codeRestart: '처음부터 다시',
  codeResend: '인증번호 다시 받기',
  codeResent: '새 인증번호를 보냈어요.',
  codeResendIn: (seconds) => `${seconds}초 뒤에 다시 받을 수 있어요`,
  codeChecking: '인증번호를 확인하는 중',
  checkEmailTitle: '메일함을 확인해 주세요',
  checkEmailBody: (email) => `${email} 로 링크를 보냈어요. 열어서 계속해 주세요.`,
  checkEmailSpam: '아직 안 왔나요? 스팸함도 살펴보세요.',
  checkEmailResend: '다시 보내기',
  checkEmailResent: '다시 보냈어요.',
  checkEmailResendIn: (seconds) => `${seconds}초 뒤에 다시 보낼 수 있어요`,
  checkEmailWrongAddress: '주소를 잘못 썼나요? 처음부터',
  landingContinue: '계속',
  legacyLinkTitle: '이 링크는 더 이상 쓰이지 않아요',
  legacyLinkBody:
    '이메일 인증 · 이메일 변경 · 본인 확인 · 계정 삭제는 이제 링크 대신 6자리 인증번호로 해요. 처음부터 다시 — 가입하거나 계정 설정을 열면 인증번호를 메일로 보내 드려요.',
  legacyLinkAction: '로그인하러 가기',
  reauthTitle: '본인 확인',
  reauthCodeHint: (email) => `본인 확인을 위해 ${email} 로 인증번호 6자리를 보내 드려요.`,
  reauthCodeSend: '인증번호 받기',
  reauthCodeSent: (email) =>
    `${email} 로 인증번호 6자리를 보냈어요. 30분 동안 쓸 수 있어요 — 누구에게도 알려 주지 마세요.`,
  reauthCodeEntered: '인증번호를 입력했어요 — 아래에서 마무리하세요.',
  reauthCodeExpired: '인증번호가 만료됐거나 다 썼어요. 새로 받아 주세요.',
  reauthProviderHint:
    '이 계정에는 이메일 주소가 없어서, 이미 쓰는 로그인 수단으로 본인 확인을 해요. 끝나면 이 화면으로 돌아와요.',
  reauthProviderButton: (provider) => `${provider} 로 확인`,
  reauthProviderNone: '본인 확인에 쓸 수 있는 로그인 수단이 없어요. 문의해 주세요.',
  reauthProviderDone: (provider) => `${provider} 로 확인했어요.`,
  linkReauthHint: (provider) => `${provider} 를 계정에 연결하려면 본인 확인이 필요해요.`,
  passwordNeedsEmail:
    '비밀번호를 정하려면 계정에 인증된 이메일 주소가 있어야 해요. 이 계정에는 없어요.',
  errorTooManyRefreshes: '세션은 멀쩡하지만 갱신을 너무 자주 했어요. 잠시 뒤에 다시 시도하세요.',
  emailChanged: '이메일 주소를 바꿨어요. 다른 기기는 로그아웃됐어요.',
  emailSendAgain: '인증번호 다시 받기',
  emailPendingNote: '인증번호는 새 주소로만 가요 — 입력하기 전에는 아무것도 바뀌지 않아요.',
  emailCodeExpired: '인증번호가 만료됐거나 다 썼어요. 새로 요청해 주세요.',
  magicLinkTitle: '로그인하는 중',
  magicLinkChecking: '링크를 확인하는 중',
  magicLinkInvalidTitle: '쓸 수 없는 로그인 링크예요',
  magicLinkInvalidBody: '만료됐거나 이미 쓴 링크일 수 있어요. 새 링크를 요청해 주세요.',
  magicLinkRequestNew: '새 링크 요청',
  magicLinkSentTitle: '메일함을 확인해 주세요',
  methodsLoading: '로그인 방법을 확인하는 중',
  methodsFailed:
    '쓸 수 있는 로그인 방법을 확인하지 못했어요. 기본 방법을 보여 드려요 — 빠진 게 있으면 다시 시도하세요.',
  methodsRetry: '다시 시도',
  forgotTitle: '비밀번호 재설정',
  forgotSubtitle: '이메일을 적으면 재설정 링크를 보내 드려요.',
  forgotSubmit: '링크 보내기',
  forgotSentTitle: '메일함을 확인해 주세요',
  forgotSentBody: (email) => `${email} 에 계정이 있다면 재설정 링크가 가고 있어요.`,
  resetTitle: '새 비밀번호 정하기',
  resetSubtitle: '모든 기기에서 로그아웃돼요.',
  resetSubmit: '비밀번호 정하기',
  resetDoneTitle: '비밀번호를 바꿨어요',
  resetDoneBody: '새 비밀번호로 로그인해 주세요.',
  resetInvalidTitle: '쓸 수 없는 링크예요',
  resetInvalidBody: '만료됐거나 이미 쓴 링크일 수 있어요. 새 링크를 요청해 주세요.',
  resetRequestNew: '새 링크 요청',
  backToSignIn: '로그인으로 돌아가기',
  callbackChecking: '로그인을 마무리하는 중',
  callbackFailedTitle: '로그인을 마치지 못했어요',
  callbackFailedBody: '제공자가 로그인을 확인해 주지 않았어요. 다시 시도해 주세요.',
  callbackConflictTitle: '이미 계정이 있어요',
  callbackCancelledTitle: '로그인을 취소했어요',
  callbackCancelledBody: '제공자 화면에서 취소해서 바뀐 것은 없어요. 원할 때 다시 시작하세요.',
  callbackStateBody:
    '이 탭에서 시작한 로그인이 아니거나 이미 끝난 로그인이에요. 로그인 화면에서 다시 시작하고, 같은 탭에서 끝내 주세요.',
  callbackConflictBody:
    '그 이메일은 다른 로그인 수단으로 이미 가입돼 있어요. 그 수단으로 로그인한 뒤 계정 설정에서 이 서비스를 연결해 주세요.',
  suspendedTitle: '정지된 계정이에요',
  suspendedBody: '이 계정은 정지됐어요. 잘못이라고 생각하면 문의해 주세요.',
  blockedTitle: '접근할 수 없어요',
  blockedBody: '이 페이지를 쓸 권한이 없어요.',
  contactSupport: '문의하기',
  settingsTitle: '계정',
  settingsIndexLabel: '계정 항목',
  sectionProfile: '프로필',
  sectionPassword: '비밀번호',
  sectionEmail: '이메일 주소',
  sectionMethods: '로그인 수단',
  sectionSessions: '로그인한 기기',
  sectionDelete: '계정 삭제',
  profileLocale: '언어',
  profileTimeZone: '시간대',
  profileLocaleDefault: '정하지 않음',
  profileSaved: '프로필을 저장했어요.',
  passwordChangeSubmit: '비밀번호 바꾸기',
  passwordSetTitle: '비밀번호 정하기',
  passwordSetHint: '지금은 비밀번호 없이 로그인하고 있어요. 비밀번호를 더할 수 있어요.',
  passwordChanged: '비밀번호를 바꿨어요. 다른 기기는 로그아웃됐어요.',
  passwordOtherSessionsNote: '바꾸면 다른 기기는 로그아웃돼요.',
  emailCurrent: '현재 주소',
  emailVerified: '인증됨',
  emailUnverified: '인증 안 됨',
  emailNew: '새 이메일',
  emailChangeSubmit: '이메일 바꾸기',
  emailNone: '이 계정에는 이메일 주소가 없어요',
  emailAddHint:
    '계정 안내와 접근 복구를 받으려면 이메일을 추가하세요. 아래에 주소를 적고, 이미 쓰는 로그인 수단으로 본인임을 확인해 주세요.',
  emailAddSubmit: '이메일 추가',
  emailPendingTitle: '새 주소의 인증번호를 입력하세요',
  emailPendingBody: (email, until) =>
    `${email} 로 인증번호 6자리를 보냈어요. 여기에 입력하면 주소가 바뀌어요${until ? ` (${until} 까지 유효해요)` : ''}. 메일이 안 오면 아래에서 다시 받으세요.`,
  methodsDescription: '이 계정에 로그인할 수 있는 방법이에요.',
  methodsLastProtected: '로그인 수단은 하나 이상 있어야 해서 이 수단은 뗄 수 없어요.',
  methodNames: { password: '비밀번호', magic_link: '이메일 링크' },
  methodLastUsed: (when) => `마지막 사용 ${when}`,
  methodNeverUsed: '아직 쓰지 않았어요',
  methodUnlink: '해제',
  methodLink: (provider) => `${provider} 연결`,
  methodUnlinkTitle: (method) => `${method} 수단을 해제할까요?`,
  methodUnlinkBody: '해제하면 이 수단으로는 로그인할 수 없어요.',
  methodUnlinked: '해제했어요.',
  methodLinkedNotice: (provider) =>
    `${provider} 를 연결했어요. 계정 주소로 알림 메일을 보냈어요 — 내가 한 일이 아니면 비밀번호를 바꾸고 다른 기기를 로그아웃하세요.`,
  methodLinked: '연결했어요.',
  sessionsDescription: '이 계정에 로그인한 기기예요.',
  sessionsCurrent: '이 기기',
  sessionsRevoke: '로그아웃',
  sessionsRevokeOthers: '다른 모든 기기 로그아웃',
  sessionsRevoked: '로그아웃했어요.',
  sessionsUnknownDevice: '알 수 없는 기기',
  sessionsLastUsed: (when) => `마지막 사용 ${when}`,
  sessionsEmpty: '다른 세션이 없어요.',
  deleteTitle: '계정 삭제',
  deleteGraceNotice: (days) =>
    `계정은 바로 삭제 처리되고 데이터는 ${days}일 뒤에 지워져요. 그 안에는 관리자가 되살릴 수 있어요.`,
  deletePasswordHint: '본인 확인을 위해 비밀번호를 입력해 주세요.',
  deleteButton: '내 계정 삭제',
  deleteDialogTitle: '계정을 삭제할까요?',
  deleteDialogBody: '모든 기기에서 로그아웃돼요. 직접 되돌릴 수 없어요.',
  deleteTypedPhrase: '삭제',
  deleteTypedLabel: '확인하려면 「삭제」를 입력하세요',
  deleteConfirm: '계정 삭제',
  deleteScheduled: (date) => `${date} 에 계정 데이터가 지워질 예정이에요.`,
  deleteDoneAction: '로그아웃',
  adminTitle: '계정 관리',
  adminSearch: '이메일로 찾기',
  adminStatusFilter: '상태',
  adminStatusAll: '전체',
  adminColumns: {
    email: '이메일',
    name: '이름',
    status: '상태',
    roles: '역할',
    created: '가입일',
    lastLogin: '마지막 로그인',
    actions: '동작',
  },
  adminStatus: { ACTIVE: '정상', SUSPENDED: '정지', DELETED: '삭제됨' },
  adminSuspend: '정지',
  adminUnsuspend: '정지 해제',
  adminRestore: '복구',
  adminGrantRole: (role) => `${role} 역할 주기`,
  adminRevokeRole: (role) => `${role} 역할 빼기`,
  adminSuspendTitle: (email) => `${email} 을(를) 정지할까요?`,
  adminSuspendReason: '사유(기록용, 본인에게는 보이지 않아요)',
  adminEmpty: '맞는 계정이 없어요.',
  adminCaption: '계정 목록',
  adminPage: (page, pages) => `${page} / ${pages} 쪽`,
  adminPrevious: '이전',
  adminNext: '다음',
  adminPurgeAfter: (date) => `${date} 에 지워짐`,
}
