import { ApiRequestError } from './types'

/**
 * 백엔드(kotlin-skeleton)가 `ApiError.code` 로 내보내는 코드. 출처별로 묶었다.
 * 코드를 추가·바꾸면 해당 Kotlin enum 과 함께 갱신한다 (임의로 만들지 않는다).
 */
export const ErrorCodes = {
  // modules/platform common/ErrorCode.kt — PlatformErrorCode
  COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
  COMMON_PARAMETER_VALIDATION_FAILED: 'COMMON.PARAMETER_VALIDATION_FAILED',
  COMMON_MALFORMED_REQUEST: 'COMMON.MALFORMED_REQUEST',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  COMMON_UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON.FORBIDDEN',
  COMMON_TOO_MANY_REQUESTS: 'COMMON.TOO_MANY_REQUESTS',
  COMMON_IDEMPOTENCY_ERROR: 'COMMON.IDEMPOTENCY_ERROR',
  COMMON_DATA_INTEGRITY_VIOLATION: 'COMMON.DATA_INTEGRITY_VIOLATION',
  COMMON_EXTERNAL_SERVICE_ERROR: 'COMMON.EXTERNAL_SERVICE_ERROR',
  COMMON_EXTERNAL_SERVICE_TIMEOUT: 'COMMON.EXTERNAL_SERVICE_TIMEOUT',
  COMMON_INTERNAL_SERVER_ERROR: 'COMMON.INTERNAL_SERVER_ERROR',

  // modules/auth auth/api/AuthErrorCode.kt
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',

  // 계정 수명주기(kotlin-skeleton docs/account-http-contract.md 10절) — AUTH.* 는 modules/auth · auth-session, ACCOUNT.* 는 modules/account
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH.EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH.ACCOUNT_SUSPENDED',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH.TOO_MANY_ATTEMPTS',
  AUTH_REFRESH_INVALID: 'AUTH.REFRESH_INVALID',
  AUTH_REFRESH_REUSED: 'AUTH.REFRESH_REUSED',
  AUTH_SESSION_NOT_FOUND: 'AUTH.SESSION_NOT_FOUND',
  AUTH_CSRF_HEADER_REQUIRED: 'AUTH.CSRF_HEADER_REQUIRED',
  ACCOUNT_TOKEN_INVALID: 'ACCOUNT.TOKEN_INVALID',
  ACCOUNT_PASSWORD_POLICY: 'ACCOUNT.PASSWORD_POLICY',
  ACCOUNT_CURRENT_PASSWORD_INVALID: 'ACCOUNT.CURRENT_PASSWORD_INVALID',
  ACCOUNT_REAUTH_FAILED: 'ACCOUNT.REAUTH_FAILED',
  ACCOUNT_CAPTCHA_FAILED: 'ACCOUNT.CAPTCHA_FAILED',
  ACCOUNT_EMAIL_TAKEN: 'ACCOUNT.EMAIL_TAKEN',
  ACCOUNT_SIGN_UP_CLOSED: 'ACCOUNT.SIGN_UP_CLOSED',
  ACCOUNT_SOCIAL_EMAIL_CONFLICT: 'ACCOUNT.SOCIAL_EMAIL_CONFLICT',
  ACCOUNT_IDENTITY_TAKEN: 'ACCOUNT.IDENTITY_TAKEN',
  ACCOUNT_IDENTITY_EXISTS: 'ACCOUNT.IDENTITY_EXISTS',
  ACCOUNT_IDENTITY_NOT_FOUND: 'ACCOUNT.IDENTITY_NOT_FOUND',
  ACCOUNT_LAST_SIGN_IN_METHOD: 'ACCOUNT.LAST_SIGN_IN_METHOD',
  ACCOUNT_LAST_ADMIN: 'ACCOUNT.LAST_ADMIN',
  ACCOUNT_SELF_ACTION_FORBIDDEN: 'ACCOUNT.SELF_ACTION_FORBIDDEN',
  ACCOUNT_NOT_FOUND: 'ACCOUNT.NOT_FOUND',
  ACCOUNT_RATE_LIMITED: 'ACCOUNT.RATE_LIMITED',
  ACCOUNT_PASSWORD_REQUIRED: 'ACCOUNT.PASSWORD_REQUIRED',
  ACCOUNT_METHOD_UNKNOWN: 'ACCOUNT.METHOD_UNKNOWN',

  // modules/auth-social auth/social/oauth/AuthSocialErrorCode.kt
  AUTH_SOCIAL_PROVIDER_NOT_FOUND: 'AUTH_SOCIAL.PROVIDER_NOT_FOUND',
  AUTH_SOCIAL_INVALID_AUTHORIZATION_CODE: 'AUTH_SOCIAL.INVALID_AUTHORIZATION_CODE',
  AUTH_SOCIAL_PROVIDER_GATEWAY_ERROR: 'AUTH_SOCIAL.PROVIDER_GATEWAY_ERROR',
  AUTH_SOCIAL_ACCOUNT_LINK_NOT_FOUND: 'AUTH_SOCIAL.ACCOUNT_LINK_NOT_FOUND',
  AUTH_SOCIAL_LINKED_ACCOUNT_NOT_FOUND: 'AUTH_SOCIAL.LINKED_ACCOUNT_NOT_FOUND',

  // modules/storage storage/web/StorageController.kt — StorageErrorCode. FILE_REJECTED 의 data.errors 가 [{ code, message }]
  STORAGE_FILE_REJECTED: 'STORAGE.FILE_REJECTED',
  STORAGE_OBJECT_NOT_FOUND: 'STORAGE.OBJECT_NOT_FOUND',
  STORAGE_UNAUTHENTICATED: 'STORAGE.UNAUTHENTICATED',

  // modules/payment payment/PaymentErrorCode.kt
  PAYMENT_PROVIDER_NOT_FOUND: 'PAYMENT.PROVIDER_NOT_FOUND',
  PAYMENT_ROUTING_FAILED: 'PAYMENT.ROUTING_FAILED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT.PROVIDER_ERROR',

  // modules/board — BoardErrorCode (kotlin-skeleton). HTTP 상태: NOT_FOUND 404 · FORBIDDEN 403 · REACTION_TYPE_INVALID · CONTENT_INVALID 400 · COMMENT_TOO_DEEP 422 · POST_NOT_COMMENTABLE · CODE_TAKEN 409 · RATE_LIMITED 429
  BOARD_NOT_FOUND: 'BOARD.NOT_FOUND',
  BOARD_POST_NOT_FOUND: 'BOARD.POST_NOT_FOUND',
  BOARD_COMMENT_NOT_FOUND: 'BOARD.COMMENT_NOT_FOUND',
  BOARD_FORBIDDEN: 'BOARD.FORBIDDEN',
  BOARD_REACTION_TYPE_INVALID: 'BOARD.REACTION_TYPE_INVALID',
  BOARD_COMMENT_TOO_DEEP: 'BOARD.COMMENT_TOO_DEEP',
  BOARD_CONTENT_INVALID: 'BOARD.CONTENT_INVALID',
  BOARD_POST_NOT_COMMENTABLE: 'BOARD.POST_NOT_COMMENTABLE',
  BOARD_CODE_TAKEN: 'BOARD.CODE_TAKEN',
  BOARD_RATE_LIMITED: 'BOARD.RATE_LIMITED',
} as const

export type ErrorCodeValue = (typeof ErrorCodes)[keyof typeof ErrorCodes]

/**
 * 프론트가 응답을 못 해석했을 때 클라이언트가 직접 채우는 코드. 백엔드가 보낸 값이 아니다.
 * (백엔드의 `HTTP.<STATUS>` 는 ApplicationException 보조 생성자가 만드는 동적 코드라 상수로 두지 않는다.)
 */
export const ClientErrorCodes = {
  /** 4xx/5xx 인데 body 가 ApiError 계약(code · title · status)을 만족하지 않음 */
  HTTP_ERROR: 'CLIENT.HTTP_ERROR',
  /** 응답 자체를 못 받음(네트워크 · 타임아웃 · 취소). status 는 0 */
  NETWORK_ERROR: 'CLIENT.NETWORK_ERROR',
} as const

/** `error` 가 [ApiRequestError] 이고 `apiError.code` 가 `codes` 중 하나면 true */
export function isErrorCode(error: unknown, codes: string | readonly string[]): boolean {
  if (!(error instanceof ApiRequestError)) return false
  return (Array.isArray(codes) ? codes : [codes]).includes(error.apiError.code)
}

/**
 * 429 가 알려 준 기다릴 시간(초). 본문 `data.retryAfterSeconds`(계약 0절)가 우선이고, 없으면 `Retry-After` 헤더.
 * 429 가 아니거나 둘 다 없으면 undefined.
 */
export function retryAfterSeconds(error: unknown): number | undefined {
  if (!(error instanceof ApiRequestError)) return undefined
  const data = error.apiError.data
  if (typeof data === 'object' && data !== null && 'retryAfterSeconds' in data) {
    const value = Number((data as { retryAfterSeconds: unknown }).retryAfterSeconds)
    if (Number.isFinite(value) && value >= 0) return value
  }
  return error.retryAfterHeader
}
